### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by XvenDeR** [omgugly/anti-shuffle#1]
It don't work, instantly sits from passenger to driver seat, no matter what.

**Comment by omgugly** [comment]
can you be more specific? because it does work. if you are entering an empty vehicle from passenger side, it will let you slide across to driver seat. this is intended functionality. if you are riding in passenger seat and the driver exits the vehicle, you will stay in passenger seat. it's easy to change but i'm not clear if that's your issue

**Comment by omgugly** [comment]
i pushed a new update that adds a config variable, 'allowEntrySlide' to the config.lua file. i believe this setting will make the script behave to your expectation. it is defaulted to false, which prevents the player from sliding to driver's seat, even if the vehicle is empty when they enter. 'allowEntrySlide' can also be toggled in-game with the chat command '/entryslide'
grab the update and let me know if that solves your issue

**Comment by XvenDeR** [comment]
yes that was the case, didn't knew that.

**Comment by XvenDeR** [comment]
thanks ;)
